//
var moment = require('moment-timezone');

// Array containing all timezones with relatives datas...
var timezones = [

	//Universal and conventional timezones...
	{timezone: "Etc/UTC", country_code: "NaNC", weather_reference: "UTC", moment: moment.tz("Etc/UTC"), color: "#1c4966"},
	{timezone: "Etc/GMT", country_code: "NaNC", weather_reference: "GMT", moment: moment.tz("Etc/GMT"), color: "#1c4966"},

	//African timezones...
	{timezone: "Africa/Abidjan", country_code: "CI", weather_reference: "Abidjan", moment: moment.tz("Africa/Abidjan"), color: "#ffdf00"},
	{timezone: "Africa/Accra", country_code: "GH", weather_reference: "Accra", moment: moment.tz("Africa/Accra"), color: "#ffdf00"},
	{timezone: "Africa/Addis_Ababa", country_code: "ET", weather_reference: "Addis Ababa", moment: moment.tz("Africa/Addis_Ababa"), color: "#ffdf00"},
	{timezone: "Africa/Algiers", country_code: "DZ", weather_reference: "Algiers", moment: moment.tz("Africa/Algiers"), color: "#ffdf00"},
	{timezone: "Africa/Asmara", country_code: "ER", weather_reference: "Asmara", moment: moment.tz("Africa/Asmara"), color: "#ffdf00"},
	{timezone: "Africa/Bamako", country_code: "ML", weather_reference: "Bamako", moment: moment.tz("Africa/Bamako"), color: "#ffdf00"},
	{timezone: "Africa/Bangui", country_code: "CF", weather_reference: "Bangui", moment: moment.tz("Africa/Bangui"), color: "#ffdf00"},
	{timezone: "Africa/Banjul", country_code: "GM", weather_reference: "Banjul", moment: moment.tz("Africa/Banjul"), color: "#ffdf00"},
	{timezone: "Africa/Bissau", country_code: "GW", weather_reference: "Bissau", moment: moment.tz("Africa/Bissau"), color: "#ffdf00"},
	{timezone: "Africa/Blantyre", country_code: "MW", weather_reference: "Blantyre", moment: moment.tz("Africa/Blantyre"), color: "#ffdf00"},
	{timezone: "Africa/Brazzaville", country_code: "CG", weather_reference: "Brazzaville", moment: moment.tz("Africa/Brazzaville"), color: "#ffdf00"},
	{timezone: "Africa/Bujumbura", country_code: "BI", weather_reference: "Bujumbura", moment: moment.tz("Africa/Bujumbura"), color: "#ffdf00"},
	{timezone: "Africa/Cairo", country_code: "EG", weather_reference: "Cairo", moment: moment.tz("Africa/Cairo"), color: "#ffdf00"},
	{timezone: "Africa/Casablanca", country_code: "MA", weather_reference: "Casablanca", moment: moment.tz("Africa/Casablanca"), color: "#ffdf00"},
	{timezone: "Africa/Ceuta", country_code: "ES", weather_reference: "Ceuta", moment: moment.tz("Africa/Ceuta"), color: "#ffdf00"},
	{timezone: "Africa/Conakry", country_code: "GN", weather_reference: "Conakry", moment: moment.tz("Africa/Conakry"), color: "#ffdf00"},
	{timezone: "Africa/Dakar", country_code: "SN", weather_reference: "Dakar", moment: moment.tz("Africa/Dakar"), color: "#ffdf00"},
	{timezone: "Africa/Dar_es_Salaam", country_code: "TZ", weather_reference: "Dar_es_Salaam", moment: moment.tz("Africa/Dar_es_Salaam"), color: "#ffdf00"},
	{timezone: "Africa/Djibouti", country_code: "DJ", weather_reference: "Djibouti", moment: moment.tz("Africa/Djibouti"), color: "#ffdf00"},
	{timezone: "Africa/Douala", country_code: "CM", weather_reference: "Douala", moment: moment.tz("Africa/Douala"), color: "#ffdf00"},
	{timezone: "Africa/El_Aaiun", country_code: "EH", weather_reference: "El_Aaiun", moment: moment.tz("Africa/El_Aaiun"), color: "#ffdf00"},
	{timezone: "Africa/Freetown", country_code: "SL", weather_reference: "Freetown", moment: moment.tz("Africa/Freetown"), color: "#ffdf00"},
	{timezone: "Africa/Gaborone", country_code: "BW", weather_reference: "Gaborone", moment: moment.tz("Africa/Gaborone"), color: "#ffdf00"},
	{timezone: "Africa/Harare", country_code: "ZW", weather_reference: "Harare", moment: moment.tz("Africa/Harare"), color: "#ffdf00"},
	{timezone: "Africa/Johannesburg", country_code: "ZA", weather_reference: "Johannesburg", moment: moment.tz("Africa/Johannesburg"), color: "#ffdf00"},
	{timezone: "Africa/Juba", country_code: "SS", weather_reference: "Juba", moment: moment.tz("Africa/Juba"), color: "#ffdf00"},
	{timezone: "Africa/Kampala", country_code: "UG", weather_reference: "Kampala", moment: moment.tz("Africa/Kampala"), color: "#ffdf00"},
	{timezone: "Africa/Khartoum", country_code: "SD", weather_reference: "Khartoum", moment: moment.tz("Africa/Khartoum"), color: "#ffdf00"},
	{timezone: "Africa/Kigali", country_code: "RW", weather_reference: "Kigali", moment: moment.tz("Africa/Kigali"), color: "#ffdf00"},
	{timezone: "Africa/Kinshasa", country_code: "CD", weather_reference: "Kinshasa", moment: moment.tz("Africa/Kinshasa"), color: "#ffdf00"},
	{timezone: "Africa/Lagos", country_code: "NG", weather_reference: "Lagos", moment: moment.tz("Africa/Lagos"), color: "#ffdf00"},
	{timezone: "Africa/Libreville", country_code: "GA", weather_reference: "Libreville", moment: moment.tz("Africa/Libreville"), color: "#ffdf00"},
	{timezone: "Africa/Lome", country_code: "TG", weather_reference: "Lome", moment: moment.tz("Africa/Lome"), color: "#ffdf00"},
	{timezone: "Africa/Luanda", country_code: "AO", weather_reference: "Luanda", moment: moment.tz("Africa/Luanda"), color: "#ffdf00"},
	{timezone: "Africa/Lubumbashi", country_code: "CD", weather_reference: "Lubumbashi", moment: moment.tz("Africa/Lubumbashi"), color: "#ffdf00"},
	{timezone: "Africa/Lusaka", country_code: "ZM", weather_reference: "Lusaka", moment: moment.tz("Africa/Lusaka"), color: "#ffdf00"},
	{timezone: "Africa/Malabo", country_code: "GQ", weather_reference: "Malabo", moment: moment.tz("Africa/Malabo"), color: "#ffdf00"},
	{timezone: "Africa/Maputo", country_code: "MZ", weather_reference: "Maputo", moment: moment.tz("Africa/Maputo"), color: "#ffdf00"},
	{timezone: "Africa/Maseru", country_code: "LS", weather_reference: "Maseru", moment: moment.tz("Africa/Maseru"), color: "#ffdf00"},
	{timezone: "Africa/Mbabane", country_code: "SZ", weather_reference: "Mbabane", moment: moment.tz("Africa/Mbabane"), color: "#ffdf00"},
	{timezone: "Africa/Mogadishu", country_code: "SO", weather_reference: "Mogadishu", moment: moment.tz("Africa/Mogadishu"), color: "#ffdf00"},
	{timezone: "Africa/Monrovia", country_code: "LR", weather_reference: "Monrovia", moment: moment.tz("Africa/Monrovia"), color: "#ffdf00"},
	{timezone: "Africa/Nairobi", country_code: "KE", weather_reference: "Nairobi", moment: moment.tz("Africa/Nairobi"), color: "#ffdf00"},
	{timezone: "Africa/Ndjamena", country_code: "TD", weather_reference: "Ndjamena", moment: moment.tz("Africa/Ndjamena"), color: "#ffdf00"},
	{timezone: "Africa/Niamey", country_code: "NE", weather_reference: "Niamey", moment: moment.tz("Africa/Niamey"), color: "#ffdf00"},
	{timezone: "Africa/Nouakchott", country_code: "MR", weather_reference: "Nouakchott", moment: moment.tz("Africa/Nouakchott"), color: "#ffdf00"},
	{timezone: "Africa/Ouagadougou", country_code: "BF", weather_reference: "Ouagadougou", moment: moment.tz("Africa/Ouagadougou"), color: "#ffdf00"},
	{timezone: "Africa/Porto-Novo", country_code: "BJ", weather_reference: "Porto-Novo", moment: moment.tz("Africa/Porto-Novo"), color: "#ffdf00"},
	{timezone: "Africa/Sao_Tome", country_code: "ST", weather_reference: "São Tomé", moment: moment.tz("Africa/Sao_Tome"), color: "#ffdf00"},
	{timezone: "Africa/Tripoli", country_code: "LY", weather_reference: "Tripoli", moment: moment.tz("Africa/Tripoli"), color: "#ffdf00"},
	{timezone: "Africa/Tunis", country_code: "TN", weather_reference: "Tunis", moment: moment.tz("Africa/Tunis"), color: "#ffdf00"},
	{timezone: "Africa/Windhoek", country_code: "NA", weather_reference: "Windhoek", moment: moment.tz("Africa/Windhoek"), color: "#ffdf00"},

	//American timezones...
	{timezone: "America/Adak", country_code: "US", weather_reference: "Adak", moment: moment.tz("America/Adak"), color: "#FFA500"},
	{timezone: "America/Anchorage", country_code: "US", weather_reference: "Anchorage", moment: moment.tz("America/Anchorage"), color: "#FFA500"},
	{timezone: "America/Anguilla", country_code: "AI", weather_reference: "Anguilla", moment: moment.tz("America/Anguilla"), color: "#FFA500"},
	{timezone: "America/Antigua", country_code: "AG", weather_reference: "Saint John's", moment: moment.tz("America/Antigua"), color: "#FFA500"},
	{timezone: "America/Araguaina", country_code: "BR", weather_reference: "Araguaina", moment: moment.tz("America/Araguaina"), color: "#FFA500"},
	{timezone: "America/Argentina/Buenos_Aires", country_code: "AR", weather_reference: "Buenos Aires", moment: moment.tz("America/Argentina/Buenos_Aires"), color: "#FFA500"},
	{timezone: "America/Argentina/Catamarca", country_code: "AR", weather_reference: "Catamarca", moment: moment.tz("America/Argentina/Catamarca"), color: "#FFA500"},
	{timezone: "America/Argentina/Cordoba", country_code: "AR", weather_reference: "Cordoba", moment: moment.tz("America/Argentina/Cordoba"), color: "#FFA500"},
	{timezone: "America/Argentina/Jujuy", country_code: "AR", weather_reference: "San Salvador de Jujuy", moment: moment.tz("America/Argentina/Jujuy"), color: "#FFA500"},
	{timezone: "America/Argentina/La_Rioja", country_code: "AR", weather_reference: "La Rioja", moment: moment.tz("America/Argentina/La_Rioja"), color: "#FFA500"},
	{timezone: "America/Argentina/Mendoza", country_code: "AR", weather_reference: "Mendoza", moment: moment.tz("America/Argentina/Mendoza"), color: "#FFA500"},
	{timezone: "America/Argentina/Rio_Gallegos", country_code: "AR", weather_reference: "Rio Gallegos", moment: moment.tz("America/Argentina/Rio_Gallegos"), color: "#FFA500"},
	{timezone: "America/Argentina/Salta", country_code: "AR", weather_reference: "Salta", moment: moment.tz("America/Argentina/Salta"), color: "#FFA500"},
	{timezone: "America/Argentina/San_Juan", country_code: "AR", weather_reference: "San Juan", moment: moment.tz("America/Argentina/San_Juan"), color: "#FFA500"},
	{timezone: "America/Argentina/San_Luis", country_code: "AR", weather_reference: "San Luis", moment: moment.tz("America/Argentina/San_Luis"), color: "#FFA500"},
	{timezone: "America/Argentina/Tucuman", country_code: "AR", weather_reference: "Tucuman", moment: moment.tz("America/Argentina/Tucuman"), color: "#FFA500"},
	{timezone: "America/Argentina/Ushuaia", country_code: "AR", weather_reference: "Ushuaia", moment: moment.tz("America/Argentina/Ushuaia"), color: "#FFA500"},
	{timezone: "America/Aruba", country_code: "AW", weather_reference: "Aruba", moment: moment.tz("America/Aruba"), color: "#FFA500"},
	{timezone: "America/Asuncion", country_code: "PY", weather_reference: "Asuncion", moment: moment.tz("America/Asuncion"), color: "#FFA500"},
	{timezone: "America/Atikokan", country_code: "CA", weather_reference: "Atikokan", moment: moment.tz("America/Atikokan"), color: "#FFA500"},
	{timezone: "America/Bahia", country_code: "BR", weather_reference: "Bahia", moment: moment.tz("America/Bahia"), color: "#FFA500"},
	{timezone: "America/Bahia_Banderas", country_code: "MX", weather_reference: "Valle de Banderas", moment: moment.tz("America/Bahia_Banderas"), color: "#FFA500"},
	{timezone: "America/Barbados", country_code: "BB", weather_reference: "Barbados", moment: moment.tz("America/Barbados"), color: "#FFA500"},
	{timezone: "America/Belem", country_code: "BR", weather_reference: "Belem", moment: moment.tz("America/Belem"), color: "#FFA500"},
	{timezone: "America/Belize", country_code: "BZ", weather_reference: "Belize", moment: moment.tz("America/Belize"), color: "#FFA500"},
	{timezone: "America/Blanc-Sablon", country_code: "CA", weather_reference: "Blanc-Sablon", moment: moment.tz("America/Blanc-Sablon"), color: "#FFA500"},
	{timezone: "America/Boa_Vista", country_code: "BR", weather_reference: "Boa Vista", moment: moment.tz("America/Boa_Vista"), color: "#FFA500"},
	{timezone: "America/Bogota", country_code: "CO", weather_reference: "Bogota", moment: moment.tz("America/Bogota"), color: "#FFA500"},
	{timezone: "America/Boise", country_code: "US", weather_reference: "Boise", moment: moment.tz("America/Boise"), color: "#FFA500"},
	{timezone: "America/Cambridge_Bay", country_code: "CA", weather_reference: "Cambridge Bay", moment: moment.tz("America/Cambridge_Bay"), color: "#FFA500"},
	{timezone: "America/Campo_Grande", country_code: "BR", weather_reference: "Campo Grande", moment: moment.tz("America/Campo_Grande"), color: "#FFA500"},
	{timezone: "America/Cancun", country_code: "MX", weather_reference: "Cancun", moment: moment.tz("America/Cancun"), color: "#FFA500"},
	{timezone: "America/Caracas", country_code: "VE", weather_reference: "Caracas", moment: moment.tz("America/Caracas"), color: "#FFA500"},
	{timezone: "America/Cayenne", country_code: "GF", weather_reference: "Cayenne", moment: moment.tz("America/Cayenne"), color: "#FFA500"},
	{timezone: "America/Cayman", country_code: "KY", weather_reference: "Cayman", moment: moment.tz("America/Cayman"), color: "#FFA500"},
	{timezone: "America/Chicago", country_code: "US", weather_reference: "Chicago", moment: moment.tz("America/Chicago"), color: "#FFA500"},
	{timezone: "America/Chihuahua", country_code: "MX", weather_reference: "Chihuahua", moment: moment.tz("America/Chihuahua"), color: "#FFA500"},
	{timezone: "America/Costa_Rica", country_code: "CR", weather_reference: "Costa Rica", moment: moment.tz("America/Costa_Rica"), color: "#FFA500"},
	{timezone: "America/Creston", country_code: "CA", weather_reference: "Creston", moment: moment.tz("America/Creston"), color: "#FFA500"},
	{timezone: "America/Cuiaba", country_code: "BR", weather_reference: "Cuiaba", moment: moment.tz("America/Cuiaba"), color: "#FFA500"},
	{timezone: "America/Curacao", country_code: "CW", weather_reference: "Curacao", moment: moment.tz("America/Curacao"), color: "#FFA500"},
	{timezone: "America/Danmarkshavn", country_code: "GL", weather_reference: "Danmarkshavn", moment: moment.tz("America/Danmarkshavn"), color: "#FFA500"},
	{timezone: "America/Dawson", country_code: "CA", weather_reference: "Dawson", moment: moment.tz("America/Dawson"), color: "#FFA500"},
	{timezone: "America/Dawson_Creek", country_code: "CA", weather_reference: "Dawson Creek", moment: moment.tz("America/Dawson_Creek"), color: "#FFA500"},
	{timezone: "America/Denver", country_code: "US", weather_reference: "Denver", moment: moment.tz("America/Denver"), color: "#FFA500"},
	{timezone: "America/Detroit", country_code: "US", weather_reference: "Detroit", moment: moment.tz("America/Detroit"), color: "#FFA500"},
	{timezone: "America/Dominica", country_code: "DM", weather_reference: "Dominica", moment: moment.tz("America/Dominica"), color: "#FFA500"},
	{timezone: "America/Edmonton", country_code: "CA", weather_reference: "Edmonton", moment: moment.tz("America/Edmonton"), color: "#FFA500"},
	{timezone: "America/Eirunepe", country_code: "BR", weather_reference: "Eirunepe", moment: moment.tz("America/Eirunepe"), color: "#FFA500"},
	{timezone: "America/El_Salvador", country_code: "SV", weather_reference: "El Salvador", moment: moment.tz("America/El_Salvador"), color: "#FFA500"},
	{timezone: "America/Fort_Nelson", country_code: "CA", weather_reference: "Fort Nelson", moment: moment.tz("America/Fort_Nelson"), color: "#FFA500"},
	{timezone: "America/Fortaleza", country_code: "CA", weather_reference: "Fortaleza", moment: moment.tz("America/Fortaleza"), color: "#FFA500"},
	{timezone: "America/Glace_Bay", country_code: "CA", weather_reference: "Glace Bay", moment: moment.tz("America/Glace_Bay"), color: "#FFA500"},
	{timezone: "America/Goose_Bay", country_code: "CA", weather_reference: "Goose Bay", moment: moment.tz("America/Goose_Bay"), color: "#FFA500"},
	{timezone: "America/Grand_Turk", country_code: "TC", weather_reference: "Cockburn Town", moment: moment.tz("America/Grand_Turk"), color: "#FFA500"},
	{timezone: "America/Grenada", country_code: "GD", weather_reference: "Grenada", moment: moment.tz("America/Grenada"), color: "#FFA500"},
	{timezone: "America/Guadeloupe", country_code: "GP", weather_reference: "Guadeloupe", moment: moment.tz("America/Guadeloupe"), color: "#FFA500"},
	{timezone: "America/Guyana", country_code: "GY", weather_reference: "Guyana", moment: moment.tz("America/Guyana"), color: "#FFA500"},
	{timezone: "America/Guayaquil", country_code: "EC", weather_reference: "Guayaquil", moment: moment.tz("America/Guayaquil"), color: "#FFA500"},
	{timezone: "America/Guyana", country_code: "GY", weather_reference: "Guyana", moment: moment.tz("America/Guyana"), color: "#FFA500"},
	{timezone: "America/Halifax", country_code: "CA", weather_reference: "Halifax", moment: moment.tz("America/Halifax"), color: "#FFA500"},
	{timezone: "America/Havana", country_code: "CU", weather_reference: "Havana", moment: moment.tz("America/Havana"), color: "#FFA500"},
	{timezone: "America/Hermosillo", country_code: "MX", weather_reference: "Hermosillo", moment: moment.tz("America/Hermosillo"), color: "#FFA500"},
	{timezone: "America/Indiana/Indianapolis", country_code: "US", weather_reference: "Indianapolis", moment: moment.tz("America/Indiana/Indianapolis"), color: "#FFA500"},
	{timezone: "America/Indiana/Knox", country_code: "US", weather_reference: "Knox", moment: moment.tz("America/Indiana/Knox"), color: "#FFA500"},
	{timezone: "America/Indiana/Marengo", country_code: "US", weather_reference: "Marengo", moment: moment.tz("America/Indiana/Marengo"), color: "#FFA500"},
	{timezone: "America/Indiana/Petersburg", country_code: "US", weather_reference: "Petersburg", moment: moment.tz("America/Indiana/Petersburg"), color: "#FFA500"},
	{timezone: "America/Indiana/Tell_City", country_code: "US", weather_reference: "Tell City", moment: moment.tz("America/Indiana/Tell_City"), color: "#FFA500"},
	{timezone: "America/Indiana/Vevay", country_code: "US", weather_reference: "Vevay", moment: moment.tz("America/Indiana/Vevay"), color: "#FFA500"},
	{timezone: "America/Indiana/Vincennes", country_code: "US", weather_reference: "Vincennes", moment: moment.tz("America/Indiana/Vincennes"), color: "#FFA500"},
	{timezone: "America/Indiana/Winamac", country_code: "US", weather_reference: "Winamac", moment: moment.tz("America/Indiana/Winamac"), color: "#FFA500"},
	{timezone: "America/Inuvik", country_code: "CA", weather_reference: "Inuvik", moment: moment.tz("America/Inuvik"), color: "#FFA500"},
	{timezone: "America/Iqaluit", country_code: "CA", weather_reference: "Iqaluit", moment: moment.tz("America/Iqaluit"), color: "#FFA500"},
	{timezone: "America/Jamaica", country_code: "JM", weather_reference: "Jamaica", moment: moment.tz("America/Jamaica"), color: "#FFA500"},
	{timezone: "America/Juneau", country_code: "US", weather_reference: "Juneau", moment: moment.tz("America/Juneau"), color: "#FFA500"},
	{timezone: "America/Kentucky/Louisville", country_code: "US", weather_reference: "Louisville", moment: moment.tz("America/Kentucky/Louisville"), color: "#FFA500"},
	{timezone: "America/Kentucky/Monticello", country_code: "US", weather_reference: "Monticello", moment: moment.tz("America/Kentucky/Monticello"), color: "#FFA500"},
	{timezone: "America/Kralendijk", country_code: "BQ", weather_reference: "Kralendijk", moment: moment.tz("America/Kralendijk"), color: "#FFA500"},
	{timezone: "America/La_Paz", country_code: "BO", weather_reference: "La Paz", moment: moment.tz("America/La_Paz"), color: "#FFA500"},
	{timezone: "America/Lima", country_code: "PM", weather_reference: "Lima", moment: moment.tz("America/Lima"), color: "#FFA500"},
	{timezone: "America/Los_Angeles", country_code: "US", weather_reference: "Los Angeles", moment: moment.tz("America/Los_Angeles"), color: "#FFA500"},
	{timezone: "America/Lower_Princes", country_code: "SX", weather_reference: "Sint Maarten", moment: moment.tz("America/Lower_Princes"), color: "#FFA500"},
	{timezone: "America/Maceio", country_code: "BR", weather_reference: "Maceio", moment: moment.tz("America/Maceio"), color: "#FFA500"},
	{timezone: "America/Managua", country_code: "NI", weather_reference: "Managua", moment: moment.tz("America/Managua"), color: "#FFA500"},
	{timezone: "America/Manaus", country_code: "BR", weather_reference: "Manaus", moment: moment.tz("America/Manaus"), color: "#FFA500"},
	{timezone: "America/Marigot", country_code: "MF", weather_reference: "Marigot", moment: moment.tz("America/Marigot"), color: "#FFA500"},
	{timezone: "America/Martinique", country_code: "MQ", weather_reference: "Martinique", moment: moment.tz("America/Martinique"), color: "#FFA500"},
	{timezone: "America/Matamoros", country_code: "MX", weather_reference: "Matamoros", moment: moment.tz("America/Matamoros"), color: "#FFA500"},
	{timezone: "America/Mazatlan", country_code: "MX", weather_reference: "Mazatlan", moment: moment.tz("America/Mazatlan"), color: "#FFA500"},
	{timezone: "America/Menominee", country_code: "US", weather_reference: "Menominee", moment: moment.tz("America/Menominee"), color: "#FFA500"},
	{timezone: "America/Merida", country_code: "MX", weather_reference: "Merida", moment: moment.tz("America/Merida"), color: "#FFA500"},
	{timezone: "America/Metlakatla", country_code: "US", weather_reference: "Metlakatla", moment: moment.tz("America/Metlakatla"), color: "#FFA500"},
	{timezone: "America/Mexico_City", country_code: "MX", weather_reference: "Mexico City", moment: moment.tz("America/Mexico_City"), color: "#FFA500"},
	{timezone: "America/Miquelon", country_code: "PM", weather_reference: "Miquelon", moment: moment.tz("America/Miquelon"), color: "#FFA500"},
	{timezone: "America/Moncton", country_code: "CA", weather_reference: "Moncton", moment: moment.tz("America/Moncton"), color: "#FFA500"},
	{timezone: "America/Monterrey", country_code: "MX", weather_reference: "Monterrey", moment: moment.tz("America/Monterrey"), color: "#FFA500"},
	{timezone: "America/Montevideo", country_code: "UY", weather_reference: "Montevideo", moment: moment.tz("America/Montevideo"), color: "#FFA500"},
	{timezone: "America/Montreal", country_code: "CA", weather_reference: "Montreal", moment: moment.tz("America/Montreal"), color: "#FFA500"},
	{timezone: "America/Montserrat", country_code: "MS", weather_reference: "Montserrat", moment: moment.tz("America/Montserrat"), color: "#FFA500"},
	{timezone: "America/Nassau", country_code: "BS", weather_reference: "Nassau", moment: moment.tz("America/Nassau"), color: "#FFA500"},
	{timezone: "America/New_York", country_code: "US", weather_reference: "New York City", moment: moment.tz("America/New_York"), color: "#FFA500"},
	{timezone: "America/Nipigon", country_code: "CA", weather_reference: "Nipigon", moment: moment.tz("America/Nipigon"), color: "#FFA500"},
	{timezone: "America/Nome", country_code: "US", weather_reference: "Nome", moment: moment.tz("America/Nome"), color: "#FFA500"},
	{timezone: "America/Noronha", country_code: "BR", weather_reference: "Noronha", moment: moment.tz("America/Noronha"), color: "#FFA500"},
	{timezone: "America/North_Dakota/Beulah", country_code: "US", weather_reference: "Beulah", moment: moment.tz("America/North_Dakota/Beulah"), color: "#FFA500"},
	{timezone: "America/North_Dakota/Center", country_code: "US", weather_reference: "Center", moment: moment.tz("America/North_Dakota/Center"), color: "#FFA500"},
	{timezone: "America/North_Dakota/New_Salem", country_code: "US", weather_reference: "New Salem", moment: moment.tz("America/North_Dakota/New_Salem"), color: "#FFA500"},
	{timezone: "America/Nuuk", country_code: "GL", weather_reference: "Nuuk", moment: moment.tz("America/Nuuk"), color: "#FFA500"},
	{timezone: "America/Ojinaga", country_code: "MX", weather_reference: "Ojinaga", moment: moment.tz("America/Ojinaga"), color: "#FFA500"},
	{timezone: "America/Panama", country_code: "PA", weather_reference: "Panama", moment: moment.tz("America/Panama"), color: "#FFA500"},
	{timezone: "America/Pangnirtung", country_code: "CA", weather_reference: "Pangnirtung", moment: moment.tz("America/Pangnirtung"), color: "#FFA500"},
	{timezone: "America/Paramaribo", country_code: "SR", weather_reference: "Paramaribo", moment: moment.tz("America/Paramaribo"), color: "#FFA500"},
	{timezone: "America/Phoenix", country_code: "US", weather_reference: "Phoenix", moment: moment.tz("America/Phoenix"), color: "#FFA500"},
	{timezone: "America/Port-au-Prince", country_code: "HT", weather_reference: "Port-au-Prince", moment: moment.tz("America/Port-au-Prince"), color: "#FFA500"},
	{timezone: "America/Port_of_Spain", country_code: "TT", weather_reference: "Port of Spain", moment: moment.tz("America/Port_of_Spain"), color: "#FFA500"},
	{timezone: "America/Porto_Velho", country_code: "BR", weather_reference: "Porto Velho", moment: moment.tz("America/Porto_Velho"), color: "#FFA500"},
	{timezone: "America/Puerto_Rico", country_code: "PR", weather_reference: "Puerto Rico", moment: moment.tz("America/Puerto_Rico"), color: "#FFA500"},
	{timezone: "America/Punta_Arenas", country_code: "CL", weather_reference: "Punta Arenas", moment: moment.tz("America/Punta_Arenas"), color: "#FFA500"},
	{timezone: "America/Rainy_River", country_code: "CA", weather_reference: "Rainy River", moment: moment.tz("America/Rainy_River"), color: "#FFA500"},
	{timezone: "America/Rankin_Inlet", country_code: "CA", weather_reference: "Rankin Inlet", moment: moment.tz("America/Rankin_Inlet"), color: "#FFA500"},
	{timezone: "America/Recife", country_code: "BR", weather_reference: "Recife", moment: moment.tz("America/Recife"), color: "#FFA500"},
	{timezone: "America/Regina", country_code: "CA", weather_reference: "Regina", moment: moment.tz("America/Regina"), color: "#FFA500"},
	{timezone: "America/Resolute", country_code: "CA", weather_reference: "Resolute", moment: moment.tz("America/Resolute"), color: "#FFA500"},
	{timezone: "America/Rio_Branco", country_code: "BR", weather_reference: "Rio Branco", moment: moment.tz("America/Rio_Branco"), color: "#FFA500"},
	{timezone: "America/Santarem", country_code: "BR", weather_reference: "Santarem", moment: moment.tz("America/Santarem"), color: "#FFA500"},
	{timezone: "America/Santiago", country_code: "CL", weather_reference: "Santiago", moment: moment.tz("America/Santiago"), color: "#FFA500"},
	{timezone: "America/Santo_Domingo", country_code: "DO", weather_reference: "Santo Domingo", moment: moment.tz("America/Santo_Domingo"), color: "#FFA500"},
	{timezone: "America/Sao_Paulo", country_code: "BR", weather_reference: "Sao Paulo", moment: moment.tz("America/Sao_Paulo"), color: "#FFA500"},
	{timezone: "America/Scoresbysund", country_code: "GL", weather_reference: "Scoresbysund", moment: moment.tz("America/Scoresbysund"), color: "#FFA500"},
	{timezone: "America/Sitka", country_code: "US", weather_reference: "Sitka", moment: moment.tz("America/Sitka"), color: "#FFA500"},
	{timezone: "America/St_Barthelemy", country_code: "BL", weather_reference: "Saint Barthelemy", moment: moment.tz("America/St_Barthelemy"), color: "#FFA500"},
	{timezone: "America/St_Johns", country_code: "CA", weather_reference: "St Johns", moment: moment.tz("America/St_Johns"), color: "#FFA500"},
	{timezone: "America/St_Kitts", country_code: "KN", weather_reference: "Saint Kitts", moment: moment.tz("America/St_Kitts"), color: "#FFA500"},
	{timezone: "America/St_Lucia", country_code: "LC", weather_reference: "Saint Lucia", moment: moment.tz("America/St_Lucia"), color: "#FFA500"},
	{timezone: "America/St_Thomas", country_code: "VI", weather_reference: "Charlotte Amalie", moment: moment.tz("America/St_Thomas"), color: "#FFA500"},
	{timezone: "America/St_Vincent", country_code: "VC", weather_reference: "Kingstown", moment: moment.tz("America/St_Vincent"), color: "#FFA500"},
	{timezone: "America/Swift_Current", country_code: "CA", weather_reference: "Swift Current", moment: moment.tz("America/Swift_Current"), color: "#FFA500"},
	{timezone: "America/Tegucigalpa", country_code: "HN", weather_reference: "Tegucigalpa", moment: moment.tz("America/Tegucigalpa"), color: "#FFA500"},
	{timezone: "America/Thule", country_code: "GL", weather_reference: "Thule", moment: moment.tz("America/Thule"), color: "#FFA500"},
	{timezone: "America/Thunder_Bay", country_code: "CA", weather_reference: "Thunder Bay", moment: moment.tz("America/Thunder_Bay"), color: "#FFA500"},
	{timezone: "America/Tijuana", country_code: "MX", weather_reference: "Tijuana", moment: moment.tz("America/Tijuana"), color: "#FFA500"},
	{timezone: "America/Toronto", country_code: "CA", weather_reference: "Toronto", moment: moment.tz("America/Toronto"), color: "#FFA500"},
	{timezone: "America/Tortola", country_code: "VG", weather_reference: "Tortola", moment: moment.tz("America/Tortola"), color: "#FFA500"},
	{timezone: "America/Vancouver", country_code: "CA", weather_reference: "Vancouver", moment: moment.tz("America/Vancouver"), color: "#FFA500"},
	{timezone: "America/Whitehorse", country_code: "CA", weather_reference: "Whitehorse", moment: moment.tz("America/Whitehorse"), color: "#FFA500"},
	{timezone: "America/Winnipeg", country_code: "CA", weather_reference: "Winnipeg", moment: moment.tz("America/Winnipeg"), color: "#FFA500"},
	{timezone: "America/Yakutat", country_code: "US", weather_reference: "Yakutat", moment: moment.tz("America/Yakutat"), color: "#FFA500"},
	{timezone: "America/Yellowknife", country_code: "CA", weather_reference: "Yellowknife", moment: moment.tz("America/Yellowknife"), color: "#FFA500"},

	//Antarctican timezones...
	{timezone: "Antarctica/Casey", country_code: "AQ", weather_reference: "Casey", moment: moment.tz("Antarctica/Casey"), color: "#FFC0CB"},
	{timezone: "Antarctica/Davis", country_code: "AQ", weather_reference: "Davis", moment: moment.tz("Antarctica/Davis"), color: "#FFC0CB"},
	{timezone: "Antarctica/DumontDUrville", country_code: "AQ", weather_reference: "DumontDUrville", moment: moment.tz("Antarctica/DumontDUrville"), color: "#FFC0CB"},
	{timezone: "Antarctica/Macquarie", country_code: "AU", weather_reference: "Macquarie", moment: moment.tz("Antarctica/Macquarie"), color: "#FFC0CB"},
	{timezone: "Antarctica/Mawson", country_code: "AQ", weather_reference: "Mawson", moment: moment.tz("Antarctica/Mawson"), color: "#FFC0CB"},
	{timezone: "Antarctica/McMurdo", country_code: "AQ", weather_reference: "McMurdo", moment: moment.tz("Antarctica/McMurdo"), color: "#FFC0CB"},
	{timezone: "Antarctica/Palmer", country_code: "AQ", weather_reference: "Palmer", moment: moment.tz("Antarctica/Palmer"), color: "#FFC0CB"},
	{timezone: "Antarctica/Rothera", country_code: "AQ", weather_reference: "Rothera", moment: moment.tz("Antarctica/Rothera"), color: "#FFC0CB"},
	{timezone: "Antarctica/Syowa", country_code: "AQ", weather_reference: "Syowa", moment: moment.tz("Antarctica/Syowa"), color: "#FFC0CB"},
	{timezone: "Antarctica/Troll", country_code: "AQ", weather_reference: "Troll", moment: moment.tz("Antarctica/Troll"), color: "#FFC0CB"},
	{timezone: "Antarctica/Vostok", country_code: "AQ", weather_reference: "Vostok", moment: moment.tz("Antarctica/Vostok"), color: "#FFC0CB"},

	//Arctic ocean's timezones...
	{timezone: "Arctic/Longyearbyen", country_code: "SJ", weather_reference: "Longyearbyen", moment: moment.tz("Arctic/Longyearbyen"), color: "#FD6C9E"},

	//Asian timezones...
	{timezone: "Asia/Almaty", country_code: "KZ", weather_reference: "Almaty", moment: moment.tz("Asia/Almaty"), color: "#79F8F8"},
	{timezone: "Asia/Amman", country_code: "JO", weather_reference: "Amman", moment: moment.tz("Asia/Amman"), color: "#79F8F8"},
	{timezone: "Asia/Anadyr", country_code: "RU", weather_reference: "Anadyr", moment: moment.tz("Asia/Anadyr"), color: "#79F8F8"},
	{timezone: "Asia/Aqtau", country_code: "KZ", weather_reference: "Aktau", moment: moment.tz("Asia/Aqtau"), color: "#79F8F8"},
	{timezone: "Asia/Aqtobe", country_code: "KZ", weather_reference: "Aqtobe", moment: moment.tz("Asia/Aqtobe"), color: "#79F8F8"},
	{timezone: "Asia/Ashgabat", country_code: "TM", weather_reference: "Ashgabat", moment: moment.tz("Asia/Ashgabat"), color: "#79F8F8"},
	{timezone: "Asia/Atyrau", country_code: "KZ", weather_reference: "Atyrau", moment: moment.tz("Asia/Atyrau"), color: "#79F8F8"},
	{timezone: "Asia/Baghdad", country_code: "IQ", weather_reference: "Baghdad", moment: moment.tz("Asia/Baghdad"), color: "#79F8F8"},
	{timezone: "Asia/Bahrain", country_code: "BH", weather_reference: "Bahrain", moment: moment.tz("Asia/Bahrain"), color: "#79F8F8"},
	{timezone: "Asia/Baku", country_code: "AZ", weather_reference: "Baku", moment: moment.tz("Asia/Baku"), color: "#79F8F8"},
	{timezone: "Asia/Bangkok", country_code: "TH", weather_reference: "Bangkok", moment: moment.tz("Asia/Bangkok"), color: "#79F8F8"},
	{timezone: "Asia/Barnaul", country_code: "RU", weather_reference: "Barnaul", moment: moment.tz("Asia/Barnaul"), color: "#79F8F8"},
	{timezone: "Asia/Beirut", country_code: "LB", weather_reference: "Beirut", moment: moment.tz("Asia/Beirut"), color: "#79F8F8"},
	{timezone: "Asia/Bishkek", country_code: "KG", weather_reference: "Bishkek", moment: moment.tz("Asia/Bishkek"), color: "#79F8F8"},
	{timezone: "Asia/Brunei", country_code: "BN", weather_reference: "Brunei", moment: moment.tz("Asia/Brunei"), color: "#79F8F8"},
	{timezone: "Asia/Chita", country_code: "RU", weather_reference: "Chita", moment: moment.tz("Asia/Chita"), color: "#79F8F8"},
	{timezone: "Asia/Choibalsan", country_code: "MN", weather_reference: "Choibalsan", moment: moment.tz("Asia/Choibalsan"), color: "#79F8F8"},
	{timezone: "Asia/Colombo", country_code: "LK", weather_reference: "Colombo", moment: moment.tz("Asia/Colombo"), color: "#79F8F8"},
	{timezone: "Asia/Damascus", country_code: "SY", weather_reference: "Damascus", moment: moment.tz("Asia/Damascus"), color: "#79F8F8"},
	{timezone: "Asia/Dhaka", country_code: "BD", weather_reference: "Dhaka", moment: moment.tz("Asia/Dhaka"), color: "#79F8F8"},
	{timezone: "Asia/Dili", country_code: "TL", weather_reference: "Dili", moment: moment.tz("Asia/Dili"), color: "#79F8F8"},
	{timezone: "Asia/Dubai", country_code: "AE", weather_reference: "Dubai", moment: moment.tz("Asia/Dubai"), color: "#79F8F8"},
	{timezone: "Asia/Dushanbe", country_code: "TJ", weather_reference: "Dushanbe", moment: moment.tz("Asia/Dushanbe"), color: "#79F8F8"},
	{timezone: "Asia/Famagusta", country_code: "CY", weather_reference: "Famagusta", moment: moment.tz("Asia/Famagusta"), color: "#79F8F8"},
	{timezone: "Asia/Gaza", country_code: "PS", weather_reference: "Gaza", moment: moment.tz("Asia/Gaza"), color: "#79F8F8"},
	{timezone: "Asia/Hebron", country_code: "PS", weather_reference: "Hebron", moment: moment.tz("Asia/Hebron"), color: "#79F8F8"},
	{timezone: "Asia/Ho_Chi_Minh", country_code: "VN", weather_reference: "Ho Chi Minh", moment: moment.tz("Asia/Ho_Chi_Minh"), color: "#79F8F8"},
	{timezone: "Asia/Hong_Kong", country_code: "HK", weather_reference: "Hong Kong", moment: moment.tz("Asia/Hong_Kong"), color: "#79F8F8"},
	{timezone: "Asia/Hovd", country_code: "MN", weather_reference: "Hovd", moment: moment.tz("Asia/Hovd"), color: "#79F8F8"},
	{timezone: "Asia/Irkutsk", country_code: "RU", weather_reference: "Irkutsk", moment: moment.tz("Asia/Irkutsk"), color: "#79F8F8"},
	{timezone: "Asia/Istanbul", country_code: "TR", weather_reference: "Istanbul", moment: moment.tz("Asia/Istanbul"), color: "#79F8F8"},
	{timezone: "Asia/Jakarta", country_code: "ID", weather_reference: "Jakarta", moment: moment.tz("Asia/Jakarta"), color: "#79F8F8"},
	{timezone: "Asia/Jayapura", country_code: "ID", weather_reference: "Jayapura", moment: moment.tz("Asia/Jayapura"), color: "#79F8F8"},
	{timezone: "Asia/Jerusalem", country_code: "IL", weather_reference: "Jerusalem", moment: moment.tz("Asia/Jerusalem"), color: "#79F8F8"},
	{timezone: "Asia/Kabul", country_code: "AF", weather_reference: "Kabul", moment: moment.tz("Asia/Kabul"), color: "#79F8F8"},
	{timezone: "Asia/Kamchatka", country_code: "RU", weather_reference: "Kamchatka", moment: moment.tz("Asia/Kamchatka"), color: "#79F8F8"},
	{timezone: "Asia/Karachi", country_code: "PK", weather_reference: "Karachi", moment: moment.tz("Asia/Karachi"), color: "#79F8F8"},
	{timezone: "Asia/Kathmandu", country_code: "NP", weather_reference: "Kathmandu", moment: moment.tz("Asia/Kathmandu"), color: "#79F8F8"},
	{timezone: "Asia/Khandyga", country_code: "RU", weather_reference: "Khandyga", moment: moment.tz("Asia/Khandyga"), color: "#79F8F8"},
	{timezone: "Asia/Kolkata", country_code: "IN", weather_reference: "Kolkata", moment: moment.tz("Asia/Kolkata"), color: "#79F8F8"},
	{timezone: "Asia/Krasnoyarsk", country_code: "RU", weather_reference: "Krasnoyarsk", moment: moment.tz("Asia/Krasnoyarsk"), color: "#79F8F8"},
	{timezone: "Asia/Kuala_Lumpur", country_code: "MY", weather_reference: "Kuala Lumpur", moment: moment.tz("Asia/Kuala_Lumpur"), color: "#79F8F8"},
	{timezone: "Asia/Kuching", country_code: "MY", weather_reference: "Kuching", moment: moment.tz("Asia/Kuching"), color: "#79F8F8"},
	{timezone: "Asia/Kuwait", country_code: "KW", weather_reference: "Kuwait", moment: moment.tz("Asia/Kuwait"), color: "#79F8F8"},
	{timezone: "Asia/Macau", country_code: "MO", weather_reference: "Macau", moment: moment.tz("Asia/Macau"), color: "#79F8F8"},
	{timezone: "Asia/Magadan", country_code: "RU", weather_reference: "Magadan", moment: moment.tz("Asia/Magadan"), color: "#79F8F8"},
	{timezone: "Asia/Makassar", country_code: "ID", weather_reference: "Makassar", moment: moment.tz("Asia/Makassar"), color: "#79F8F8"},
	{timezone: "Asia/Manila", country_code: "PH", weather_reference: "Manila", moment: moment.tz("Asia/Manila"), color: "#79F8F8"},
	{timezone: "Asia/Muscat", country_code: "OM", weather_reference: "Muscat", moment: moment.tz("Asia/Muscat"), color: "#79F8F8"},
	{timezone: "Asia/Nicosia", country_code: "CY", weather_reference: "Nicosia", moment: moment.tz("Asia/Nicosia"), color: "#79F8F8"},
	{timezone: "Asia/Novokuznetsk", country_code: "RU", weather_reference: "Novokuznetsk", moment: moment.tz("Asia/Novokuznetsk"), color: "#79F8F8"},
	{timezone: "Asia/Novosibirsk", country_code: "RU", weather_reference: "Novosibirsk", moment: moment.tz("Asia/Novosibirsk"), color: "#79F8F8"},
	{timezone: "Asia/Omsk", country_code: "RU", weather_reference: "Omsk", moment: moment.tz("Asia/Omsk"), color: "#79F8F8"},
	{timezone: "Asia/Oral", country_code: "KZ", weather_reference: "Oral", moment: moment.tz("Asia/Oral"), color: "#79F8F8"},
	{timezone: "Asia/Phnom_Penh", country_code: "KH", weather_reference: "Phnom Penh", moment: moment.tz("Asia/Phnom_Penh"), color: "#79F8F8"},
	{timezone: "Asia/Pontianak", country_code: "ID", weather_reference: "Pontianak", moment: moment.tz("Asia/Pontianak"), color: "#79F8F8"},
	{timezone: "Asia/Pyongyang", country_code: "KP", weather_reference: "Pyongyang", moment: moment.tz("Asia/Pyongyang"), color: "#79F8F8"},
	{timezone: "Asia/Qatar", country_code: "QA", weather_reference: "Qatar", moment: moment.tz("Asia/Qatar"), color: "#79F8F8"},
	{timezone: "Asia/Qostanay", country_code: "KZ", weather_reference: "Qostanay", moment: moment.tz("Asia/Qostanay"), color: "#79F8F8"},
	{timezone: "Asia/Qyzylorda", country_code: "KZ", weather_reference: "Qyzylorda", moment: moment.tz("Asia/Qyzylorda"), color: "#79F8F8"},
	{timezone: "Asia/Riyadh", country_code: "SA", weather_reference: "Riyadh", moment: moment.tz("Asia/Riyadh"), color: "#79F8F8"},
	{timezone: "Asia/Sakhalin", country_code: "RU", weather_reference: "Yuzhno-Sakhalinsk", moment: moment.tz("Asia/Sakhalin"), color: "#79F8F8"},
	{timezone: "Asia/Samarkand", country_code: "UZ", weather_reference: "Samarkand", moment: moment.tz("Asia/Samarkand"), color: "#79F8F8"},
	{timezone: "Asia/Seoul", country_code: "KR", weather_reference: "Seoul", moment: moment.tz("Asia/Seoul"), color: "#79F8F8"},
	{timezone: "Asia/Shanghai", country_code: "CN", weather_reference: "Shanghai", moment: moment.tz("Asia/Shanghai"), color: "#79F8F8"},
	{timezone: "Asia/Singapore", country_code: "SG", weather_reference: "Singapore", moment: moment.tz("Asia/Singapore"), color: "#79F8F8"},
	{timezone: "Asia/Srednekolymsk", country_code: "RU", weather_reference: "Srednekolymsk", moment: moment.tz("Asia/Srednekolymsk"), color: "#79F8F8"},
	{timezone: "Asia/Taipei", country_code: "TW", weather_reference: "Taipei", moment: moment.tz("Asia/Taipei"), color: "#79F8F8"},
	{timezone: "Asia/Tashkent", country_code: "UZ", weather_reference: "Tashkent", moment: moment.tz("Asia/Tashkent"), color: "#79F8F8"},
	{timezone: "Asia/Tbilisi", country_code: "GE", weather_reference: "Tbilisi", moment: moment.tz("Asia/Tbilisi"), color: "#79F8F8"},
	{timezone: "Asia/Tehran", country_code: "IR", weather_reference: "Tehran", moment: moment.tz("Asia/Tehran"), color: "#79F8F8"},
	{timezone: "Asia/Thimphu", country_code: "BT", weather_reference: "Thimphu", moment: moment.tz("Asia/Thimphu"), color: "#79F8F8"},
	{timezone: "Asia/Tokyo", country_code: "JP", weather_reference: "Tokyo", moment: moment.tz("Asia/Tokyo"), color: "#79F8F8"},
	{timezone: "Asia/Tomsk", country_code: "RU", weather_reference: "Tomsk", moment: moment.tz("Asia/Tomsk"), color: "#79F8F8"},
	{timezone: "Asia/Ulaanbaatar", country_code: "MN", weather_reference: "Ulaanbaatar", moment: moment.tz("Asia/Ulaanbaatar"), color: "#79F8F8"},
	{timezone: "Asia/Urumqi", country_code: "CN", weather_reference: "Urumqi", moment: moment.tz("Asia/Urumqi"), color: "#79F8F8"},
	{timezone: "Asia/Ust-Nera", country_code: "RU", weather_reference: "Ust-Nera", moment: moment.tz("Asia/Ust-Nera"), color: "#79F8F8"},
	{timezone: "Asia/Vientiane", country_code: "LA", weather_reference: "Vientiane", moment: moment.tz("Asia/Vientiane"), color: "#79F8F8"},
	{timezone: "Asia/Vladivostok", country_code: "RU", weather_reference: "Vladivostok", moment: moment.tz("Asia/Vladivostok"), color: "#79F8F8"},
	{timezone: "Asia/Yakutsk", country_code: "RU", weather_reference: "Yakutsk", moment: moment.tz("Asia/Yakutsk"), color: "#79F8F8"},
	{timezone: "Asia/Yangon", country_code: "MM", weather_reference: "Yangon", moment: moment.tz("Asia/Yangon"), color: "#79F8F8"},
	{timezone: "Asia/Yekaterinburg", country_code: "RU", weather_reference: "Yekaterinburg", moment: moment.tz("Asia/Yekaterinburg"), color: "#79F8F8"},
	{timezone: "Asia/Yerevan", country_code: "AM", weather_reference: "Yerevan", moment: moment.tz("Asia/Yerevan"), color: "#79F8F8"},

	//Atlantic ocean's timezones...
	{timezone: "Atlantic/Azores", country_code: "PT", weather_reference: "Azores", moment: moment.tz("Atlantic/Azores"), color: "#00FF00"},
	{timezone: "Atlantic/Bermuda", country_code: "BM", weather_reference: "Bermuda", moment: moment.tz("Atlantic/Bermuda"), color: "#00FF00"},
	{timezone: "Atlantic/Canary", country_code: "ES", weather_reference: "Canary", moment: moment.tz("Atlantic/Canary"), color: "#00FF00"},
	{timezone: "Atlantic/Cape_Verde", country_code: "CV", weather_reference: "Praia", moment: moment.tz("Atlantic/Cape_Verde"), color: "#00FF00"},
	{timezone: "Atlantic/Faroe", country_code: "FO", weather_reference: "Tórshavn", moment: moment.tz("Atlantic/Faroe"), color: "#00FF00"},
	{timezone: "Atlantic/Madeira", country_code: "PT", weather_reference: "Madeira", moment: moment.tz("Atlantic/Madeira"), color: "#00FF00"},
	{timezone: "Atlantic/Reykjavik", country_code: "IS", weather_reference: "Reykjavik", moment: moment.tz("Atlantic/Reykjavik"), color: "#00FF00"},
	{timezone: "Atlantic/South_Georgia", country_code: "GS", weather_reference: "Grytviken", moment: moment.tz("Atlantic/South_Georgia"), color: "#00FF00"},
	{timezone: "Atlantic/St_Helena", country_code: "SH", weather_reference: "Jamestown", moment: moment.tz("Atlantic/St_Helena"), color: "#00FF00"},
	{timezone: "Atlantic/Stanley", country_code: "FK", weather_reference: "Stanley", moment: moment.tz("Atlantic/Stanley"), color: "#00FF00"},

	//Australian timezones...
	{timezone: "Australia/Adelaide", country_code: "AU", weather_reference: "Adelaide", moment: moment.tz("Australia/Adelaide"), color: "#0091AD"},
	{timezone: "Australia/Brisbane", country_code: "AU", weather_reference: "Brisbane", moment: moment.tz("Australia/Brisbane"), color: "#0091AD"},
	{timezone: "Australia/Broken_Hill", country_code: "AU", weather_reference: "Broken Hill", moment: moment.tz("Australia/Broken_Hill"), color: "#0091AD"},
	{timezone: "Australia/Currie", country_code: "AU", weather_reference: "Currie", moment: moment.tz("Australia/Currie"), color: "#0091AD"},
	{timezone: "Australia/Darwin", country_code: "AU", weather_reference: "Darwin", moment: moment.tz("Australia/Darwin"), color: "#0091AD"},
	{timezone: "Australia/Eucla", country_code: "AU", weather_reference: "Eucla", moment: moment.tz("Australia/Eucla"), color: "#0091AD"},
	{timezone: "Australia/Hobart", country_code: "AU", weather_reference: "Hobart", moment: moment.tz("Australia/Hobart"), color: "#0091AD"},
	{timezone: "Australia/Lindeman", country_code: "AU", weather_reference: "Lindeman", moment: moment.tz("Australia/Lindeman"), color: "#0091AD"},
	{timezone: "Australia/Lord_Howe", country_code: "AU", weather_reference: "Lord Howe", moment: moment.tz("Australia/Lord_Howe"), color: "#0091AD"},
	{timezone: "Australia/Melbourne", country_code: "AU", weather_reference: "Melbourne", moment: moment.tz("Australia/Melbourne"), color: "#0091AD"},
	{timezone: "Australia/Perth", country_code: "AU", weather_reference: "Perth", moment: moment.tz("Australia/Perth"), color: "#0091AD"},
	{timezone: "Australia/Sydney", country_code: "AU", weather_reference: "Sydney", moment: moment.tz("Australia/Sydney"), color: "#0091AD"},

	//European timezones...
	{timezone: "Europe/Amsterdam", country_code: "NL", weather_reference: "Amsterdam", moment: moment.tz("Europe/Amsterdam"), color: "#006400"},
	{timezone: "Europe/Andorra", country_code: "AD", weather_reference: "Andorra", moment: moment.tz("Europe/Andorra"), color: "#006400"},
	{timezone: "Europe/Astrakhan", country_code: "RU", weather_reference: "Astrakhan", moment: moment.tz("Europe/Astrakhan"), color: "#006400"},
	{timezone: "Europe/Athens", country_code: "GR", weather_reference: "Athens", moment: moment.tz("Europe/Athens"), color: "#006400"},
	{timezone: "Europe/Belgrade", country_code: "RS", weather_reference: "Belgrade", moment: moment.tz("Europe/Belgrade"), color: "#006400"},
	{timezone: "Europe/Berlin", country_code: "DE", weather_reference: "Berlin", moment: moment.tz("Europe/Berlin"), color: "#006400"},
	{timezone: "Europe/Bratislava", country_code: "SK", weather_reference: "Bratislava", moment: moment.tz("Europe/Bratislava"), color: "#006400"},
	{timezone: "Europe/Brussels", country_code: "BE", weather_reference: "Brussels", moment: moment.tz("Europe/Brussels"), color: "#006400"},
	{timezone: "Europe/Bucharest", country_code: "RO", weather_reference: "Bucharest", moment: moment.tz("Europe/Bucharest"), color: "#006400"},
	{timezone: "Europe/Budapest", country_code: "HU", weather_reference: "Budapest", moment: moment.tz("Europe/Budapest"), color: "#006400"},
	{timezone: "Europe/Busingen", country_code: "DE", weather_reference: "Busingen", moment: moment.tz("Europe/Busingen"), color: "#006400"},
	{timezone: "Europe/Chisinau", country_code: "MD", weather_reference: "Chisinau", moment: moment.tz("Europe/Chisinau"), color: "#006400"},
	{timezone: "Europe/Copenhagen", country_code: "DK", weather_reference: "Copenhagen", moment: moment.tz("Europe/Copenhagen"), color: "#006400"},
	{timezone: "Europe/Dublin", country_code: "IE", weather_reference: "Dublin", moment: moment.tz("Europe/Dublin"), color: "#006400"},
	{timezone: "Europe/Gibraltar", country_code: "GI", weather_reference: "Gibraltar", moment: moment.tz("Europe/Gibraltar"), color: "#006400"},
	{timezone: "Europe/Guernsey", country_code: "GG", weather_reference: "Guernsey", moment: moment.tz("Europe/Guernsey"), color: "#006400"},
	{timezone: "Europe/Helsinki", country_code: "FI", weather_reference: "Helsinki", moment: moment.tz("Europe/Helsinki"), color: "#006400"},
	{timezone: "Europe/Isle_of_Man", country_code: "IM", weather_reference: "Douglas", moment: moment.tz("Europe/Isle_of_Man"), color: "#006400"},
	{timezone: "Europe/Istanbul", country_code: "TR", weather_reference: "Istanbul", moment: moment.tz("Europe/Istanbul"), color: "#006400"},
	{timezone: "Europe/Jersey", country_code: "JE", weather_reference: "Jersey", moment: moment.tz("Europe/Jersey"), color: "#006400"},
	{timezone: "Europe/Kaliningrad", country_code: "RU", weather_reference: "Kaliningrad", moment: moment.tz("Europe/Kaliningrad"), color: "#006400"},
	{timezone: "Europe/Kiev", country_code: "UA", weather_reference: "Kiev", moment: moment.tz("Europe/Kiev"), color: "#006400"},
	{timezone: "Europe/Kirov", country_code: "RU", weather_reference: "Kirov", moment: moment.tz("Europe/Kirov"), color: "#006400"},
	{timezone: "Europe/Lisbon", country_code: "PT", weather_reference: "Lisbon", moment: moment.tz("Europe/Lisbon"), color: "#006400"},
	{timezone: "Europe/Ljubljana", country_code: "SI", weather_reference: "Ljubljana", moment: moment.tz("Europe/Ljubljana"), color: "#006400"},
	{timezone: "Europe/London", country_code: "GB", weather_reference: "London", moment: moment.tz("Europe/London"), color: "#006400"},
	{timezone: "Europe/Luxembourg", country_code: "LU", weather_reference: "Luxembourg", moment: moment.tz("Europe/Luxembourg"), color: "#006400"},
	{timezone: "Europe/Madrid", country_code: "ES", weather_reference: "Madrid", moment: moment.tz("Europe/Madrid"), color: "#006400"},
	{timezone: "Europe/Malta", country_code: "MT", weather_reference: "Valletta", moment: moment.tz("Europe/Malta"), color: "#006400"},
	{timezone: "Europe/Mariehamn", country_code: "AX", weather_reference: "Mariehamn", moment: moment.tz("Europe/Mariehamn"), color: "#006400"},
	{timezone: "Europe/Minsk", country_code: "BY", weather_reference: "Minsk", moment: moment.tz("Europe/Minsk"), color: "#006400"},
	{timezone: "Europe/Monaco", country_code: "MC", weather_reference: "Monaco", moment: moment.tz("Europe/Monaco"), color: "#006400"},
	{timezone: "Europe/Moscow", country_code: "RU", weather_reference: "Moscow", moment: moment.tz("Europe/Moscow"), color: "#006400"},
	{timezone: "Europe/Nicosia", country_code: "CY", weather_reference: "Nicosia", moment: moment.tz("Europe/Nicosia"), color: "#006400"},
	{timezone: "Europe/Oslo", country_code: "NO", weather_reference: "Oslo", moment: moment.tz("Europe/Oslo"), color: "#006400"},
	{timezone: "Europe/Paris", country_code: "FR", weather_reference: "Paris", moment: moment.tz("Europe/Paris"), color: "#006400"},
	{timezone: "Europe/Podgorica", country_code: "ME", weather_reference: "Podgorica", moment: moment.tz("Europe/Podgorica"), color: "#006400"},
	{timezone: "Europe/Prague", country_code: "CZ", weather_reference: "Prague", moment: moment.tz("Europe/Prague"), color: "#006400"},
	{timezone: "Europe/Riga", country_code: "LV", weather_reference: "Riga", moment: moment.tz("Europe/Riga"), color: "#006400"},
	{timezone: "Europe/Rome", country_code: "IT", weather_reference: "Rome", moment: moment.tz("Europe/Rome"), color: "#006400"},
	{timezone: "Europe/Samara", country_code: "RU", weather_reference: "Samara", moment: moment.tz("Europe/Samara"), color: "#006400"},
	{timezone: "Europe/San_Marino", country_code: "SM", weather_reference: "San_Marino", moment: moment.tz("Europe/San_Marino"), color: "#006400"},
	{timezone: "Europe/Sarajevo", country_code: "BA", weather_reference: "Sarajevo", moment: moment.tz("Europe/Sarajevo"), color: "#006400"},
	{timezone: "Europe/Saratov", country_code: "RU", weather_reference: "Saratov", moment: moment.tz("Europe/Saratov"), color: "#006400"},
	{timezone: "Europe/Simferopol", country_code: "UA", weather_reference: "Simferopol", moment: moment.tz("Europe/Simferopol"), color: "#006400"},
	{timezone: "Europe/Skopje", country_code: "MK", weather_reference: "Skopje", moment: moment.tz("Europe/Skopje"), color: "#006400"},
	{timezone: "Europe/Sofia", country_code: "BG", weather_reference: "Sofia", moment: moment.tz("Europe/Sofia"), color: "#006400"},
	{timezone: "Europe/Stockholm", country_code: "SE", weather_reference: "Stockholm", moment: moment.tz("Europe/Stockholm"), color: "#006400"},
	{timezone: "Europe/Tallinn", country_code: "EE", weather_reference: "Tallinn", moment: moment.tz("Europe/Tallinn"), color: "#006400"},
	{timezone: "Europe/Tirane", country_code: "AL", weather_reference: "Tirana", moment: moment.tz("Europe/Tirane"), color: "#006400"},
	{timezone: "Europe/Ulyanovsk", country_code: "RU", weather_reference: "Ulyanovsk", moment: moment.tz("Europe/Ulyanovsk"), color: "#006400"},
	{timezone: "Europe/Uzhgorod", country_code: "UA", weather_reference: "Uzhgorod", moment: moment.tz("Europe/Uzhgorod"), color: "#006400"},
	{timezone: "Europe/Vaduz", country_code: "LI", weather_reference: "Vaduz", moment: moment.tz("Europe/Vaduz"), color: "#006400"},
	{timezone: "Europe/Vatican", country_code: "VA", weather_reference: "Vatican", moment: moment.tz("Europe/Vatican"), color: "#006400"},
	{timezone: "Europe/Vienna", country_code: "AT", weather_reference: "Vienna", moment: moment.tz("Europe/Vienna"), color: "#006400"},
	{timezone: "Europe/Vilnius", country_code: "LT", weather_reference: "Vilnius", moment: moment.tz("Europe/Vilnius"), color: "#006400"},
	{timezone: "Europe/Volgograd", country_code: "RU", weather_reference: "Volgograd", moment: moment.tz("Europe/Volgograd"), color: "#006400"},
	{timezone: "Europe/Warsaw", country_code: "PL", weather_reference: "Warsaw", moment: moment.tz("Europe/Warsaw"), color: "#006400"},
	{timezone: "Europe/Zagreb", country_code: "HR", weather_reference: "Zagreb", moment: moment.tz("Europe/Zagreb"), color: "#006400"},
	{timezone: "Europe/Zaporozhye", country_code: "UA", weather_reference: "Zaporozhye", moment: moment.tz("Europe/Zaporozhye"), color: "#006400"},
	{timezone: "Europe/Zurich", country_code: "CH", weather_reference: "Zurich", moment: moment.tz("Europe/Zurich"), color: "#006400"},

	//Indian ocean's timezones...
	{timezone: "Indian/Antananarivo", country_code: "MG", weather_reference: "Antananarivo", moment: moment.tz("Indian/Antananarivo"), color: "#33FFA2"},
	{timezone: "Indian/Chagos", country_code: "IO", weather_reference: "Camp Thunder Cove", moment: moment.tz("Indian/Chagos"), color: "#33FFA2"},
	{timezone: "Indian/Christmas", country_code: "CX", weather_reference: "Flying Fish Cove", moment: moment.tz("Indian/Christmas"), color: "#33FFA2"},
	{timezone: "Indian/Cocos", country_code: "CC", weather_reference: "West Island", moment: moment.tz("Indian/Cocos"), color: "#33FFA2"},
	{timezone: "Indian/Comoro", country_code: "KM", weather_reference: "Moroni", moment: moment.tz("Indian/Comoro"), color: "#33FFA2"},
	{timezone: "Indian/Kerguelen", country_code: "TF", weather_reference: "Kerguelen", moment: moment.tz("Indian/Kerguelen"), color: "#33FFA2"},
	{timezone: "Indian/Mahe", country_code: "SC", weather_reference: "Victoria", moment: moment.tz("Indian/Mahe"), color: "#33FFA2"},
	{timezone: "Indian/Maldives", country_code: "MV", weather_reference: "Male", moment: moment.tz("Indian/Maldives"), color: "#33FFA2"},
	{timezone: "Indian/Mauritius", country_code: "MU", weather_reference: "Port Louis", moment: moment.tz("Indian/Mauritius"), color: "#33FFA2"},
	{timezone: "Indian/Mayotte", country_code: "YT", weather_reference: "Mamoudzou", moment: moment.tz("Indian/Mayotte"), color: "#33FFA2"},
	{timezone: "Indian/Reunion", country_code: "RE", weather_reference: "Saint-Denis", moment: moment.tz("Indian/Reunion"), color: "#33FFA2"},

	//Pacific ocean's timezones...
	{timezone: "Pacific/Apia", country_code: "WS", weather_reference: "Apia", moment: moment.tz("Pacific/Apia"), color: "#4B0082"},
	{timezone: "Pacific/Auckland", country_code: "NZ", weather_reference: "Auckland", moment: moment.tz("Pacific/Auckland"), color: "#4B0082"},
	{timezone: "Pacific/Bougainville", country_code: "PG", weather_reference: "Bougainville", moment: moment.tz("Pacific/Bougainville"), color: "#4B0082"},
	{timezone: "Pacific/Chatham", country_code: "NZ", weather_reference: "Waitangi", moment: moment.tz("Pacific/Chatham"), color: "#4B0082"},
	{timezone: "Pacific/Chuuk", country_code: "FM", weather_reference: "Chuuk", moment: moment.tz("Pacific/Chuuk"), color: "#4B0082"},
	{timezone: "Pacific/Easter", country_code: "CL", weather_reference: "Hanga Roa", moment: moment.tz("Pacific/Easter"), color: "#4B0082"},
	{timezone: "Pacific/Efate", country_code: "VU", weather_reference: "Port-Vila", moment: moment.tz("Pacific/Efate"), color: "#4B0082"},
	{timezone: "Pacific/Enderbury", country_code: "KI", weather_reference: "Port-Vila", moment: moment.tz("Pacific/Enderbury"), color: "#4B0082"},
	{timezone: "Pacific/Fakaofo", country_code: "TK", weather_reference: "Fale Old Settlement", moment: moment.tz("Pacific/Fakaofo"), color: "#4B0082"},
	{timezone: "Pacific/Fiji", country_code: "FJ", weather_reference: "Suva", moment: moment.tz("Pacific/Fiji"), color: "#4B0082"},
	{timezone: "Pacific/Funafuti", country_code: "TV", weather_reference: "Funafuti", moment: moment.tz("Pacific/Funafuti"), color: "#4B0082"},
	{timezone: "Pacific/Galapagos", country_code: "EC", weather_reference: "Puerto Baquerizo Moreno", moment: moment.tz("Pacific/Galapagos"), color: "#4B0082"},
	{timezone: "Pacific/Gambier", country_code: "PF", weather_reference: "Rikitea", moment: moment.tz("Pacific/Gambier"), color: "#4B0082"},
	{timezone: "Pacific/Guadalcanal", country_code: "SB", weather_reference: "Honiara", moment: moment.tz("Pacific/Guadalcanal"), color: "#4B0082"},
	{timezone: "Pacific/Guam", country_code: "GU", weather_reference: "Hagåtña", moment: moment.tz("Pacific/Guam"), color: "#4B0082"},
	{timezone: "Pacific/Honolulu", country_code: "US", weather_reference: "Honolulu", moment: moment.tz("Pacific/Honolulu"), color: "#4B0082"},
	{timezone: "Pacific/Kiritimati", country_code: "KI", weather_reference: "Kiritimati", moment: moment.tz("Pacific/Kiritimati"), color: "#4B0082"},
	{timezone: "Pacific/Kosrae", country_code: "FM", weather_reference: "Kosrae", moment: moment.tz("Pacific/Kosrae"), color: "#4B0082"},
	{timezone: "Pacific/Kwajalein", country_code: "MH", weather_reference: "Kwajalein", moment: moment.tz("Pacific/Kwajalein"), color: "#4B0082"},
	{timezone: "Pacific/Majuro", country_code: "MH", weather_reference: "Majuro", moment: moment.tz("Pacific/Majuro"), color: "#4B0082"},
	{timezone: "Pacific/Marquesas", country_code: "PF", weather_reference: "Taiohae", moment: moment.tz("Pacific/Marquesas"), color: "#4B0082"},
	{timezone: "Pacific/Midway", country_code: "US", weather_reference: "Midway", moment: moment.tz("Pacific/Midway"), color: "#4B0082"},
	{timezone: "Pacific/Nauru", country_code: "NR", weather_reference: "Nauru", moment: moment.tz("Pacific/Nauru"), color: "#4B0082"},
	{timezone: "Pacific/Niue", country_code: "NU", weather_reference: "Niue", moment: moment.tz("Pacific/Niue"), color: "#4B0082"},
	{timezone: "Pacific/Norfolk", country_code: "NF", weather_reference: "Norfolk", moment: moment.tz("Pacific/Norfolk"), color: "#4B0082"},
	{timezone: "Pacific/Noumea", country_code: "NC", weather_reference: "Noumea", moment: moment.tz("Pacific/Noumea"), color: "#4B0082"},
	{timezone: "Pacific/Pago_Pago", country_code: "AS", weather_reference: "Pago Pago", moment: moment.tz("Pacific/Pago_Pago"), color: "#4B0082"},
	{timezone: "Pacific/Palau", country_code: "PW", weather_reference: "Palau", moment: moment.tz("Pacific/Palau"), color: "#4B0082"},
	{timezone: "Pacific/Pitcairn", country_code: "PN", weather_reference: "Pitcairn", moment: moment.tz("Pacific/Pitcairn"), color: "#4B0082"},
	{timezone: "Pacific/Pohnpei", country_code: "FM", weather_reference: "Pohnpei", moment: moment.tz("Pacific/Pohnpei"), color: "#4B0082"},
	{timezone: "Pacific/Port_Moresby", country_code: "PG", weather_reference: "Port-Moresby", moment: moment.tz("Pacific/Port_Moresby"), color: "#4B0082"},
	{timezone: "Pacific/Rarotonga", country_code: "CK", weather_reference: "Avarua", moment: moment.tz("Pacific/Rarotonga"), color: "#4B0082"},
	{timezone: "Pacific/Saipan", country_code: "MP", weather_reference: "Saipan", moment: moment.tz("Pacific/Saipan"), color: "#4B0082"},
	{timezone: "Pacific/Tahiti", country_code: "PF", weather_reference: "Tarawa", moment: moment.tz("Pacific/Tahiti"), color: "#4B0082"},
	{timezone: "Pacific/Tarawa", country_code: "KI", weather_reference: "Tarawa", moment: moment.tz("Pacific/Tarawa"), color: "#4B0082"},
	{timezone: "Pacific/Tongatapu", country_code: "TO", weather_reference: "Tongatapu", moment: moment.tz("Pacific/Tongatapu"), color: "#4B0082"},
	{timezone: "Pacific/Wake", country_code: "UM", weather_reference: "Wake", moment: moment.tz("Pacific/Wake"), color: "#4B0082"},
	{timezone: "Pacific/Wallis", country_code: "WF", weather_reference: "Mata-Utu", moment: moment.tz("Pacific/Wallis"), color: "#4B0082"}
];

// Definition of the 'getCountryCodeFromTimezone' function to identify and return the country code of the 'wishedTimezone' timezone...
function getCountryCodeFromTimezone(wishedTimezone) {

	// Definition of the 'wishedCountryCode' variable which will contain the found country code...
	var wishedCountryCode = "";

	// Browse for each element contained in the 'timezones' array...
	for(var i = 0; i < timezones.length; i++)
	{
		// If the current element of the 'timezones' array corresponds to the desired timezone...
		if(timezones[i].timezone === wishedTimezone) {

			// Affectation of the found country code to the 'wishedCountryCode' variable...
			wishedCountryCode = timezones[i].country_code;

			// Leaving the loop...
			break;
		}
	}

	return wishedCountryCode;
}

// Export the 'timezones' array and the 'moment' object...
module.exports = {
	'timezones': timezones,
	'getCountryCodeFromTimezone': getCountryCodeFromTimezone,
	'moment': moment
}